# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_icontact}
  s.version = "0.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stephen Eley"]
  s.date = %q{2009-08-14}
  s.default_executable = %q{icontact}
  s.description = %q{ActsAsIcontact connects Ruby applications with the iContact e-mail marketing service using the iContact API v2.0.  Building on the RestClient gem, it offers two significant feature sets:

* Simple, consistent access to all resources in the iContact API; and
* Automatic synchronizing between ActiveRecord models and iContact contact lists for Rails applications.
}
  s.email = %q{sfeley@gmail.com}
  s.executables = ["icontact"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE.txt",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "acts_as_icontact.gemspec",
     "bin/icontact",
     "init.rb",
     "lib/acts_as_icontact.rb",
     "lib/acts_as_icontact/command_line/completion.rb",
     "lib/acts_as_icontact/command_line/variables.rb",
     "lib/acts_as_icontact/config.rb",
     "lib/acts_as_icontact/connection.rb",
     "lib/acts_as_icontact/exceptions.rb",
     "lib/acts_as_icontact/rails.rb",
     "lib/acts_as_icontact/rails/callbacks.rb",
     "lib/acts_as_icontact/rails/lists.rb",
     "lib/acts_as_icontact/rails/macro.rb",
     "lib/acts_as_icontact/rails/mappings.rb",
     "lib/acts_as_icontact/readonly.rb",
     "lib/acts_as_icontact/resource.rb",
     "lib/acts_as_icontact/resource_collection.rb",
     "lib/acts_as_icontact/resources/account.rb",
     "lib/acts_as_icontact/resources/campaign.rb",
     "lib/acts_as_icontact/resources/client.rb",
     "lib/acts_as_icontact/resources/contact.rb",
     "lib/acts_as_icontact/resources/contact_history.rb",
     "lib/acts_as_icontact/resources/custom_field.rb",
     "lib/acts_as_icontact/resources/list.rb",
     "lib/acts_as_icontact/resources/message.rb",
     "lib/acts_as_icontact/resources/message_bounces.rb",
     "lib/acts_as_icontact/resources/message_clicks.rb",
     "lib/acts_as_icontact/resources/message_opens.rb",
     "lib/acts_as_icontact/resources/message_statistics.rb",
     "lib/acts_as_icontact/resources/segment.rb",
     "lib/acts_as_icontact/resources/segment_criteria.rb",
     "lib/acts_as_icontact/resources/subscription.rb",
     "lib/acts_as_icontact/subresource.rb",
     "rails/init.rb",
     "spec/config_spec.rb",
     "spec/connection_spec.rb",
     "spec/examples/schema.rb",
     "spec/rails_spec.rb",
     "spec/rails_spec/callbacks_spec.rb",
     "spec/rails_spec/mappings_spec.rb",
     "spec/resource_collection_spec.rb",
     "spec/resource_spec.rb",
     "spec/resources/account_spec.rb",
     "spec/resources/campaign_spec.rb",
     "spec/resources/clientfolder_spec.rb",
     "spec/resources/contact_history_spec.rb",
     "spec/resources/contact_spec.rb",
     "spec/resources/custom_field_spec.rb",
     "spec/resources/list_spec.rb",
     "spec/resources/message_spec.rb",
     "spec/resources/segment_spec.rb",
     "spec/resources/subscription_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/support/active_record/connection_adapters/nulldb_adapter.rb",
     "spec/support/nulldb_rspec.rb",
     "spec/support/spec_fakeweb.rb"
  ]
  s.homepage = %q{http://github.com/SFEley/acts_as_icontact}
  s.rdoc_options = ["--charset=UTF-8", "--all"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{actsasicontact}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Automatic bridge between iContact e-mail marketing service and Rails ActiveRecord}
  s.test_files = [
    "spec/config_spec.rb",
     "spec/connection_spec.rb",
     "spec/examples/schema.rb",
     "spec/rails_spec/callbacks_spec.rb",
     "spec/rails_spec/mappings_spec.rb",
     "spec/rails_spec.rb",
     "spec/resource_collection_spec.rb",
     "spec/resource_spec.rb",
     "spec/resources/account_spec.rb",
     "spec/resources/campaign_spec.rb",
     "spec/resources/clientfolder_spec.rb",
     "spec/resources/contact_history_spec.rb",
     "spec/resources/contact_spec.rb",
     "spec/resources/custom_field_spec.rb",
     "spec/resources/list_spec.rb",
     "spec/resources/message_spec.rb",
     "spec/resources/segment_spec.rb",
     "spec/resources/subscription_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/active_record/connection_adapters/nulldb_adapter.rb",
     "spec/support/nulldb_rspec.rb",
     "spec/support/spec_fakeweb.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 1.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_runtime_dependency(%q<bond>, [">= 0.1.4"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, [">= 1.0"])
      s.add_dependency(%q<activesupport>, [">= 2.3.2"])
      s.add_dependency(%q<bond>, [">= 0.1.4"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 1.0"])
    s.add_dependency(%q<activesupport>, [">= 2.3.2"])
    s.add_dependency(%q<bond>, [">= 0.1.4"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end
